### ISSUE TITLE
image-prep script reorder needed

### ISSUE THREAD

**Issue by aebling** [JNPRAutomate/space-packer#11]
Uncommenting the fix vmx cp in the script thus moving it up broke the logic. Unfortunately it copies the fixed vmx with the 2nd disk info is too soon in the process. It gets overwritten with the ovftool creation of the ova. Thus in the vmx directory for output we have the vmx file from the ova creation not the modified version.

**Comment by routelastresort** [comment]
There's no reason for this anyway, as the .VMX is modified in Packer.

``` json
      "vmx_data": {
        "ide0:0.startConnected": "FALSE",
        "scsi1:0.present": "TRUE",
        "scsi1:0.deviceType": "disk",
        "scsi1:0.fileName": "space-{{user `space_version`}}-disk2-cl1.vmdk",
        "scsi1:0.mode": "persistent",
        "scsi1.virtualDev": "lsilogic",
        "scsi1.present": "TRUE",
        "ethernet0.connectionType": "nat",
        "ethernet1.connectionType": "nat",
        "ethernet2.connectionType": "nat",
        "ethernet3.connectionType": "nat"
      }
```

I thought I took it out.  We shouldn't need any fixes at this time...

**Comment by aebling** [comment]
Ok cool. Just something I had noticed. I still cannot try packer until they release the 0.7.2

**Comment by routelastresort** [comment]
I can walk you through building it, or just send you binaries.
